export { default as TimeFast } from './time-fast.svg'
export { default as ConnectionRelation } from './connection-relation.svg'
export { default as Logo } from './logo.svg'
export { default as GovLogo } from './gov-logo.svg'
export { default as Saly } from './saly.svg'
