import { PublicLayout } from '@/components'
import { Chip } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'

const IndexPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Chip label="Chip Filled" />

        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default IndexPage
IndexPage.getLayout = (page) => <PublicLayout>{page}</PublicLayout>
